version: 0.0
os: windows
files:
  - source: \obj\Debug\netcoreapp2.1
    destination: C:\inetpub\wwwroot\DotNetCoreHelloWorld
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900